services:
  db:
    container_name: damas_paia-db
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=paia
      - POSTGRES_DB=damas_paia
    ports:
      - "5432:5432"
  backend:
    container_name: damas_paia
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
     