services:
  backend:
    container_name: sv
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - .env
  database:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${DB_NAME},${TEST_DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
        - ./scripts/create-multiples-dbs.sh:/docker-entrypoint-initdb.d/create-multiples-dbs.sh