services:
  backend:
    container_name: sv
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - .env
  database:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=paia
      - POSTGRES_DB=damas_paia
    env_file:
      - .env
    