services:
  backend:
    container_name: sv
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - .env
  database:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env